# -*- coding: utf-8 -*-
"""메인 페이지 문구.  [T] = 전문용어, glossary.md 참고"""

TITLE = {"ko": "HF 로지스틱스", "en": "HF Logistics", "zh": "HF物流"}
DESC = {
 "ko": "컨테이너 한 박스부터 40톤 중장비까지, 인천에서 시작하는 물류. 국제물류주선과 중장비 운반을 두 축으로 운영하는 주식회사 에이치에프로지스틱스.",
 "en": "From a single container to 40-tonne construction equipment. HF Logistics runs freight forwarding and heavy cargo transport from Incheon, Korea.",
 "zh": "从一个集装箱到40吨重型设备，物流始于仁川。HF物流以国际物流运输代理和重型设备运输为两大支柱。",
}

# 히어로 3슬라이드
HERO = {
 "ko": [
  {"eb":"Sea Freight / FCL · LCL", "h":"모든 화물을<br><em>정기 스케줄</em>에 싣습니다",
   "p":"중국 위해 집화 창고에서 한국행 화물을 모아 혼재합니다. 소량 화물도 매주 정해진 마감에 맞춰 인천항 보세창고로 들어옵니다. 선복 확보와 선적 서류를 한 창구에서 관리합니다.",
   "a1":"부킹 · 견적 요청", "a2":"해상운송 자세히", "l2":"services.html#forwarding",
   "tab":"해상운송 FCL · LCL"},
  {"eb":"Air Freight / Incheon FTZ", "h":"항공 서비스는<br><em>공항에서 시작</em>합니다",
   "p":"인천공항 자유무역지역 창고로 반입해 보세 상태에서 보관하고 통관합니다. 보세운송 · 통관 · 하역을 일괄 처리해, 화물 성격에 따라 리드타임과 비용을 함께 조절합니다.",
   "a1":"항공 견적 요청", "a2":"창고 인프라 보기", "l2":"network.html",
   "tab":"항공운송 · 자유무역지역"},
  {"eb":"Heavy Cargo / RO-RO · Flat Rack", "h":"모든 중장비를<br><em>한 창구</em>에서 처리합니다",
   "p":"중국 공장 상차부터 RO-RO 선적, 인천항 · 평택항 중량물 하역, 저상 트레일러 현장 하차까지. 구간마다 업체가 바뀌지 않으므로 진행 상황을 한 곳에서 확인할 수 있습니다.",
   "a1":"중장비 견적 요청", "a2":"중장비 부문 보기", "l2":"heavy.html",
   "tab":"중장비 · 중량물 운송"},
 ],
 "en": [
  {"eb":"Sea Freight / FCL · LCL", "h":"All cargo moves<br>on a <em>fixed schedule</em>",
   "p":"We consolidate Korea-bound cargo at our Weihai warehouse in China. Small shipments make the weekly cut-off and arrive at our bonded warehouse in Incheon Port. Space booking and shipping documents are handled through one desk.",
   "a1":"Book or request a quote", "a2":"About sea freight", "l2":"services.html#forwarding",
   "tab":"Sea Freight FCL · LCL"},
  {"eb":"Air Freight / Incheon FTZ", "h":"Our air service starts<br><em>right at the airport</em>",
   "p":"Cargo enters our warehouse in the Incheon Airport Free Trade Zone and is stored and cleared under bond. Bonded transport, customs clearance and handling run as one service, so lead time and cost can be tuned to the shipment.",
   "a1":"Request an air quote", "a2":"See our facilities", "l2":"network.html",
   "tab":"Air Freight · Free Trade Zone"},
  {"eb":"Heavy Cargo / RO-RO · Flat Rack", "h":"All heavy equipment,<br>handled through <em>one desk</em>",
   "p":"From loading at the Chinese factory through RO-RO shipment, heavy-lift discharge at Incheon or Pyeongtaek Port, to final drop-off by low-bed trailer. No hand-offs between vendors, so you track progress in one place.",
   "a1":"Request a heavy cargo quote", "a2":"Heavy cargo division", "l2":"heavy.html",
   "tab":"Heavy Cargo Transport"},
 ],
 "zh": [
  {"eb":"Sea Freight / FCL · LCL", "h":"所有货物，<br>都能搭上<em>定期班期</em>",
   "p":"我们在中国威海的集货仓库集中拼装发往韩国的货物。小批量货物也能赶上每周固定截关，直接进入仁川港保税仓库。舱位预订与提单等单证由同一窗口统一处理。",
   "a1":"订舱 · 报价咨询", "a2":"了解海运服务", "l2":"services.html#forwarding",
   "tab":"海运 FCL · LCL"},
  {"eb":"Air Freight / Incheon FTZ", "h":"空运服务，<br><em>直接从机场</em>开始",
   "p":"货物进入仁川机场自由贸易区仓库，在保税状态下存储并办理通关。保税运输、通关、装卸一体化处理，可根据货物性质同时调整时效与成本。",
   "a1":"空运报价咨询", "a2":"查看仓储设施", "l2":"network.html",
   "tab":"空运 · 自由贸易区"},
  {"eb":"Heavy Cargo / RO-RO · Flat Rack", "h":"所有工程机械，<br><em>一个窗口</em>到底",
   "p":"从中国工厂装车、滚装船装运、仁川港与平泽港重件卸货，到低平板拖车送抵工地卸车。全程不更换承运方，进度可在一处查询。",
   "a1":"重型设备报价咨询", "a2":"查看重型设备业务", "l2":"heavy.html",
   "tab":"重型设备运输"},
 ],
}

# 사실 스트립
FACTS = {
 "ko": [("2,600","평","인천항 보세창고 실내면적","야드 1,815평 · 특허보세구역"),
        ("2","곳","보세 반입 거점","인천항 · 인천공항 자유무역지역"),
        ("3","개","중국 집화 거점","위해 운영 중 · 심천 · 항저우 예정"),
        ("40","톤","중장비까지 단일 창구 처리","소형 택배 화물부터 건설기계까지")],
 "en": [("8,600","m²","Indoor bonded warehouse, Incheon Port","Plus 6,000 m² yard · Licensed bonded area"),
        ("2","sites","Bonded entry points","Incheon Port · Incheon Airport FTZ"),
        ("3","hubs","Consolidation hubs in China","Weihai live · Shenzhen &amp; Hangzhou planned"),
        ("40","t","Handled through one desk","From parcels to construction equipment")],
 "zh": [("8,600","㎡","仁川港保税仓库室内面积","另有堆场6,000㎡ · 特许保税区"),
        ("2","处","保税入库据点","仁川港 · 仁川机场自由贸易区"),
        ("3","个","中国集货据点","威海运营中 · 深圳、杭州筹备中"),
        ("40","吨","最重可单一窗口处理","从小件快递到工程机械")],
}

# 사업 2축
DIVS = {
 "ko": [{"tag":"Division 01","h":"종합물류 부문","sub":"수입 화물의 국제 구간부터 국내 수취인까지",
         "items":[("국제물류주선 (포워딩)","해상 · 항공"),("제3자물류 (3PL) · 풀필먼트","보관 · 출고 · 반품"),
                  ("전자상거래 물류","통관 연계 배송대행"),("수출입 대행 · 무역업","소싱 · 계약 · 선적")],
         "btn":"서비스 상세","link":"services.html"},
        {"tag":"Division 02","h":"중장비 부문","sub":"중국 공장에서 국내 현장까지, 장비 전용 물류",
         "items":[("중기 · 건설기계 수입 운송","중국 &rarr; 한국"),("중량물 통관 · 요건 관리","수입 요건 확인"),
                  ("차량 및 중장비 운반업","부두 &rarr; 현장"),("중기 및 건설기계 매매업","거래 및 중개")],
         "btn":"중장비 상세","link":"heavy.html"}],
 "en": [{"tag":"Division 01","h":"Logistics","sub":"From the international leg to the door in Korea",
         "items":[("Freight forwarding","Sea · Air"),("3PL &amp; fulfilment","Storage · Outbound · Returns"),
                  ("E-commerce logistics","Clearance-linked delivery"),("Trade &amp; sourcing agency","Sourcing · Contracts · Shipping")],
         "btn":"View services","link":"services.html"},
        {"tag":"Division 02","h":"Heavy Cargo","sub":"From the Chinese factory to the Korean site",
         "items":[("Construction equipment import","China &rarr; Korea"),("Heavy-lift clearance &amp; compliance","Import requirement checks"),
                  ("Vehicle &amp; equipment haulage","Port &rarr; Site"),("Equipment trading","Sales &amp; brokerage")],
         "btn":"View heavy cargo","link":"heavy.html"}],
 "zh": [{"tag":"Division 01","h":"综合物流","sub":"从国际段到韩国境内收货人",
         "items":[("国际物流运输代理","海运 · 空运"),("第三方物流(3PL) · 履约配送","仓储 · 出库 · 退货"),
                  ("跨境电商物流","通关联动配送代理"),("进出口代理 · 贸易","选品 · 签约 · 装运")],
         "btn":"查看服务详情","link":"services.html"},
        {"tag":"Division 02","h":"重型设备","sub":"从中国工厂到韩国施工现场的专用物流",
         "items":[("工程机械进口运输","中国 &rarr; 韩国"),("重件通关 · 要件管理","进口要件确认"),
                  ("车辆及重型设备运输","码头 &rarr; 现场"),("工程机械买卖","交易及中介")],
         "btn":"查看重型设备","link":"heavy.html"}],
}

# 섹션 제목 (제목, 영문 병기 라벨, 아이브로우)
SEC = {
 "ko": {"div":("두 개의 축, 하나의 운영 체계","Divisions","Business Structure"),
        "sch":("주간 집화 · 선적 스케줄","WK 38","Weekly Consolidation Schedule"),
        "svc":("사업영역","6 Areas","Services"),
        "net":("중국 집화 거점 &harr; 한국 반입 창고","China / Korea","Network"),
        "why":("HF를 선택해야 하는 이유","","Why HF Logistics"),
        "con":("화물은 멈추지 않아야 합니다","","Contact")},
 "en": {"div":("Two divisions, one operation","Divisions","Business Structure"),
        "sch":("Weekly consolidation schedule","WK 38","Weekly Consolidation Schedule"),
        "svc":("What we do","6 Areas","Services"),
        "net":("China hubs &harr; Korea warehouses","China / Korea","Network"),
        "why":("Why shippers choose HF","","Why HF Logistics"),
        "con":("Cargo should never stop","","Contact")},
 "zh": {"div":("两大支柱，一套运营体系","Divisions","Business Structure"),
        "sch":("每周集货 · 装运班期","WK 38","Weekly Consolidation Schedule"),
        "svc":("业务范围","6 Areas","Services"),
        "net":("中国集货据点 &harr; 韩国入库仓库","China / Korea","Network"),
        "why":("选择HF的理由","","Why HF Logistics"),
        "con":("货物不应停下","","Contact")},
}

# 주간 스케줄 표
SCHED = {
 "ko": {"cols":["Route 노선","Mode","Closing 집화마감","ETD","Space 선복"],
        "rows":[("위해 &rarr; 인천항","LCL","09-17 水","09-19","open","여유"),
                ("위해 &rarr; 인천항","FCL","09-18 木","09-20","tight","마감 임박"),
                ("위해 &rarr; 인천공항","AIR","매일 마감","매일","open","여유"),
                ("중국 &rarr; 인천항","RO-RO","선적 협의","월 2회","ask","중장비 문의"),
                ("심천 &rarr; 인천항","LCL","&mdash;","&mdash;","ask","개설 예정"),
                ("항저우 &rarr; 인천항","LCL","&mdash;","&mdash;","ask","개설 예정")],
        "btn":"부킹 · 선복 문의",
        "note":"위 일정은 화면 구성을 위한 예시입니다. 실제 마감 · 선복 현황은 운영팀이 매주 갱신하며, 확정 일정은 담당자가 확인 후 안내드립니다."},
 "en": {"cols":["Route","Mode","Closing","ETD","Space"],
        "rows":[("Weihai &rarr; Incheon Port","LCL","Wed 09-17","09-19","open","Open"),
                ("Weihai &rarr; Incheon Port","FCL","Thu 09-18","09-20","tight","Closing soon"),
                ("Weihai &rarr; Incheon Airport","AIR","Daily","Daily","open","Open"),
                ("China &rarr; Incheon Port","RO-RO","On request","2 / month","ask","Enquire"),
                ("Shenzhen &rarr; Incheon Port","LCL","&mdash;","&mdash;","ask","Planned"),
                ("Hangzhou &rarr; Incheon Port","LCL","&mdash;","&mdash;","ask","Planned")],
        "btn":"Booking &amp; space enquiry",
        "note":"The dates above are sample data used for layout. Our operations team updates cut-offs and space weekly, and a coordinator confirms the actual schedule with you."},
 "zh": {"cols":["航线 Route","方式 Mode","截货 Closing","ETD","舱位 Space"],
        "rows":[("威海 &rarr; 仁川港","LCL","09-17 周三","09-19","open","有舱"),
                ("威海 &rarr; 仁川港","FCL","09-18 周四","09-20","tight","即将截关"),
                ("威海 &rarr; 仁川机场","AIR","每日截货","每日","open","有舱"),
                ("中国 &rarr; 仁川港","RO-RO","装运面议","每月2班","ask","重件请咨询"),
                ("深圳 &rarr; 仁川港","LCL","&mdash;","&mdash;","ask","筹备中"),
                ("杭州 &rarr; 仁川港","LCL","&mdash;","&mdash;","ask","筹备中")],
        "btn":"订舱 · 舱位咨询",
        "note":"以上班期为页面示例数据。实际截关与舱位由运营团队每周更新，确定班期将由专属负责人确认后告知。"},
}

# 사업영역 7 + CTA
SVCS = {
 "ko": [("services.html#forwarding","국제물류주선","Forwarding","해상 · 항공 수출입 운송 주선, 선복 확보 및 서류 일괄 관리"),
        ("heavy.html","차량 및 중장비 운반업","Heavy Cargo","중국산 건설기계의 해상 운송 주선 및 부두에서 현장까지 육상 운송"),
        ("services.html#tpl","제3자물류 (3PL)","Logistics","화주사 물류 기능 전반 위탁 운영, 운송 · 보관 · 재고 · 정산 통합"),
        ("services.html#tpl","풀필먼트","Fulfillment","입고 검수부터 피킹 · 패킹 · 출고, 반품 회수 및 재입고까지"),
        ("heavy.html#requirements","중기 · 건설기계 수출입","Equipment","중국 건설기계 수입 통관 대행 및 장비 매매 · 중개"),
        ("services.html#ecommerce","전자상거래 · 통신판매중개","E-Commerce","해외 셀러 및 플랫폼 연계 구매대행 · 배송대행 서비스"),
        ("repair.html","보세창고 보관 · 보수작업","Bonded","보세 상태에서 표시 · 포장 문제를 직접 처리해 반송 없이 통관")],
 "en": [("services.html#forwarding","Freight forwarding","Forwarding","Sea and air import/export forwarding, space booking and document control"),
        ("heavy.html","Vehicle &amp; heavy equipment haulage","Heavy Cargo","Ocean transport of Chinese construction equipment and inland haulage from port to site"),
        ("services.html#tpl","Third-party logistics (3PL)","Logistics","Outsourced logistics operations covering transport, storage, inventory and settlement"),
        ("services.html#tpl","Fulfilment","Fulfillment","Inbound inspection through picking, packing, outbound, returns and restocking"),
        ("heavy.html#requirements","Equipment import &amp; export","Equipment","Customs clearance for Chinese construction equipment, plus trading and brokerage"),
        ("services.html#ecommerce","E-commerce &amp; marketplace support","E-Commerce","Purchasing and delivery agency services for overseas sellers and platforms"),
        ("repair.html","Bonded storage &amp; reconditioning","Bonded","Fixing labelling and packaging faults under bond so cargo clears without being returned")],
 "zh": [("services.html#forwarding","国际物流运输代理","Forwarding","海运、空运进出口运输代理，舱位预订及单证统一管理"),
        ("heavy.html","车辆及重型设备运输","Heavy Cargo","中国产工程机械海运代理，以及从码头到施工现场的陆运"),
        ("services.html#tpl","第三方物流 (3PL)","Logistics","受托运营货主物流全流程，整合运输、仓储、库存与结算"),
        ("services.html#tpl","履约配送","Fulfillment","从入库验货到拣货、包装、出库，以及退货回收与重新入库"),
        ("heavy.html#requirements","工程机械进出口","Equipment","中国工程机械进口通关代理及设备买卖、中介"),
        ("services.html#ecommerce","跨境电商 · 网络销售中介","E-Commerce","面向海外卖家及平台的代购、代发货服务"),
        ("repair.html","保税仓储 · 整理作业","Bonded","在保税状态下直接处理标签与包装问题，无需退运即可通关")],
}
SVCS_CTA = {"ko":("품목과 노선만 알려주시면<br>담당자가 배정됩니다","견적 요청"),
            "en":("Tell us the commodity and route,<br>and we assign a coordinator","Request a quote"),
            "zh":("只需告知品名与航线，<br>我们即刻指派负责人","报价咨询")}
SVCS_NOTE = {"ko":"※ 이 외 물류 창고업 및 보관통관사업, 운수물류 아웃소싱사업 등을 정관 목적사업으로 보유하고 있습니다.",
             "en":"Our articles of incorporation also cover warehousing, bonded clearance operations and logistics outsourcing.",
             "zh":"※ 此外，公司章程还包含物流仓储业、保税通关业务、运输物流外包业务等经营范围。"}

# 네트워크
NODES = {
 "ko": {"cn":"China · 중국 집화 거점","kr":"Korea · 한국 반입 창고",
   "cnrows":[("위해","威海 / Weihai","LCL 혼재 창고 · 전자상거래 배대지 2개 동 운영","live","운영 중"),
             ("심천","深圳 / Shenzhen","화남 지역 집화 거점","plan","확보 예정"),
             ("항저우","杭州 / Hangzhou","화동 지역 집화 거점","plan","확보 예정")],
   "krrows":[("인천항","Sea Cargo","보세창고 · 특허보세구역<br>협력사 ㈜스카이국제운송","live","보수작업 가능"),
             ("인천공항","Air Cargo","자유무역지역 내 보세 보관<br>협력사 삼복로지스틱㈜","live","보세 보관"),
             ("인천 본사","HQ","인천광역시 중구 서해대로 342<br>인천세관 인접","live","운영 중")],
   "btn":"네트워크 상세",
   "lede":"항공과 해상을 나눠 운영합니다. 급한 화물은 공항 자유무역지역 창고로, 중량 · 대량 화물은 인천항 보세창고로 받습니다. 화물 성격에 따라 리드타임과 비용을 함께 조절할 수 있습니다."},
 "en": {"cn":"China · Consolidation hubs","kr":"Korea · Receiving warehouses",
   "cnrows":[("Weihai","威海","LCL consolidation warehouse and e-commerce forwarding depot, two units","live","Live"),
             ("Shenzhen","深圳","Hub for southern China","plan","Planned"),
             ("Hangzhou","杭州","Hub for eastern China","plan","Planned")],
   "krrows":[("Incheon Port","Sea Cargo","Bonded warehouse, licensed bonded area<br>Partner: Sky International Transport","live","Reconditioning available"),
             ("Incheon Airport","Air Cargo","Bonded storage inside the Free Trade Zone<br>Partner: Sambok Logistic","live","Bonded storage"),
             ("Incheon HQ","HQ","342 Seohae-daero, Jung-gu, Incheon<br>Next to Incheon Customs","live","Live")],
   "btn":"Network in detail",
   "lede":"Air and sea run on separate tracks. Urgent cargo goes to the airport Free Trade Zone warehouse; heavy or high-volume cargo goes to the bonded warehouse at Incheon Port. Lead time and cost can be tuned to the shipment."},
 "zh": {"cn":"China · 中国集货据点","kr":"Korea · 韩国入库仓库",
   "cnrows":[("威海","Weihai","LCL拼箱仓库 · 跨境电商转运仓，共2栋运营中","live","运营中"),
             ("深圳","Shenzhen","华南地区集货据点","plan","筹备中"),
             ("杭州","Hangzhou","华东地区集货据点","plan","筹备中")],
   "krrows":[("仁川港","Sea Cargo","保税仓库 · 特许保税区<br>合作方 Sky国际运输","live","可做整理作业"),
             ("仁川机场","Air Cargo","自由贸易区内保税存储<br>合作方 三福物流","live","保税存储"),
             ("仁川总部","HQ","仁川广域市中区西海大路342号<br>毗邻仁川海关","live","运营中")],
   "btn":"查看网络详情",
   "lede":"空运与海运分线运营。急件送往机场自由贸易区仓库，重货与大批量货物则进入仁川港保税仓库。可根据货物性质同时调整时效与成本。"},
}

# 통관 대응 (다크 슬랩)
CUSTOMS = {
 "ko": {"eb":"Customs Capability","h":"제도는 바뀌었습니다.<br>준비된 물류만 멈추지 않습니다.",
   "lede":"2026년 전자상거래 전용 통관플랫폼 시행으로 수입화주 검증과 업체 등록 요건이 대폭 강화되었습니다. 당사는 제도 변경에 맞춘 검증 · 알림 체계를 갖추고 통관 지연을 최소화합니다.",
   "btn":"통관 대응 상세",
   "steps":[("수입화주 정보 사전 검증","개인통관고유부호 · 성명 · 연락처 · 주소 일치 여부를 출고 전 단계에서 사전 확인합니다."),
            ("미승인 건 실시간 알림","현장 스캔 시 승인 / 미승인 상태를 즉시 확인해 보류 화물의 체류 시간을 줄입니다."),
            ("전자상거래업자 부호 관리","개정 관세법에 따른 업자 등록 및 전용 수입신고서 · 통관목록 기재에 대응합니다."),
            ("관세사 · 전문 솔루션 연계","통관 전문 파트너와 협업하여 품목 분류 및 요건 확인 리스크를 최소화합니다.")]},
 "en": {"eb":"Customs Capability","h":"The rules changed.<br>Only prepared logistics keeps moving.",
   "lede":"Korea's dedicated e-commerce customs platform, in force from 2026, sharply tightened importer verification and operator registration. We have built the matching verification and alerting workflow to keep clearance delays to a minimum.",
   "btn":"Customs capability in detail",
   "steps":[("Importer details verified in advance","We check the personal customs clearance code, name, phone number and address against each other before goods leave the warehouse."),
            ("Real-time alerts on unapproved shipments","Approval status is read at the moment of scanning, cutting the time held cargo sits in the warehouse."),
            ("E-commerce operator code management","We handle operator registration under the amended Customs Act and the dedicated declaration and manifest entries."),
            ("Licensed customs brokers and specialist tools","We work with clearance specialists to reduce risk in tariff classification and requirement checks.")]},
 "zh": {"eb":"Customs Capability","h":"制度已经改变，<br>只有准备好的物流不会停。",
   "lede":"随着2026年跨境电商专用通关平台施行，进口货主验证与企业登记要求大幅收紧。我们已建立与新制度相匹配的验证与提醒机制，将通关延误降到最低。",
   "btn":"查看通关应对详情",
   "steps":[("进口货主信息事前验证","在出库前核对个人通关唯一编码、姓名、联系方式与地址是否一致。"),
            ("未批准件实时提醒","现场扫描时即刻确认批准与否，缩短滞留货物的停留时间。"),
            ("跨境电商企业代码管理","按修订后的关税法办理企业登记，并对应专用进口申报单与通关清单的填写。"),
            ("对接报关师与专业系统","与通关专业伙伴协作，降低品目归类与要件确认方面的风险。")]},
}

# 선택 이유
WHY = {
 "ko": [("인천항 · 인천세관 인접","본사와 운영 거점이 인천 중구에 위치합니다. 컨테이너 화물도, 중장비 부두 반입도 현장 대응 속도가 다릅니다."),
        ("일반 화물과 중량물을 한 곳에서","소형 택배 화물부터 40톤 건설기계까지 한 회사가 처리합니다. 업체를 나눠 쓰며 책임 공방할 일이 없습니다."),
        ("제도 변화 선제 대응","2026년 전자상거래 통관 개편에 맞춰 검증 · 알림 체계를 갖췄습니다. 제도 리스크를 화주사가 떠안지 않도록 합니다."),
        ("중국 현지부터 국내 현장까지","중장비는 부두에 내려놓는다고 끝이 아닙니다. 공장 상차부터 통관 · 현장 하차까지 한 창구로 갑니다.")],
 "en": [("Next to Incheon Port and Customs","Our head office and operations sit in Jung-gu, Incheon. That proximity shows in how fast we respond, for containers and for heavy equipment alike."),
        ("General cargo and heavy lift in one place","One company handles everything from small parcels to 40-tonne machines. No splitting work between vendors and no arguments over who is responsible."),
        ("Ahead of regulatory change","We built our verification and alerting workflow for Korea's 2026 e-commerce customs reform, so the regulatory risk does not land on the shipper."),
        ("From the Chinese factory to the Korean site","Heavy equipment is not finished when it lands at the quay. Loading at the factory, clearance and final drop-off all run through one desk.")],
 "zh": [("毗邻仁川港与仁川海关","总部与运营据点位于仁川中区。无论是集装箱货物还是重型设备进港，现场响应速度都不一样。"),
        ("普货与重件一站处理","从小件快递到40吨工程机械，由一家公司完成。无需分包给多家，也不会出现责任推诿。"),
        ("提前应对制度变化","已按2026年跨境电商通关改革建立验证与提醒机制，不让制度风险落到货主身上。"),
        ("从中国现场到韩国工地","重型设备卸到码头并不算结束。从工厂装车到通关、现场卸车，全程一个窗口。")],
}

ASK = {
 "ko": [("품목과 HS코드","요건 확인이 필요한 품목인지 먼저 판단합니다"),
        ("출발지 · 운송 구간","중국 어느 지역에서 출발하는지, 해상인지 항공인지"),
        ("물량과 규격","CBM · 중량, 중장비라면 모델명과 전고 · 전장"),
        ("납기 · 인도 현장","언제까지, 어디로 들어가야 하는지")],
 "en": [("Commodity and HS code","So we can tell straight away whether import requirements apply"),
        ("Origin and mode","Which part of China it ships from, and whether by sea or air"),
        ("Volume and dimensions","CBM and weight — for equipment, the model plus height and length"),
        ("Deadline and delivery site","By when, and where it has to arrive")],
 "zh": [("品名与HS编码","便于先行判断是否属于需确认要件的品目"),
        ("起运地与运输方式","从中国哪个地区起运，走海运还是空运"),
        ("货量与规格","体积与重量；若为重型设备，请提供型号及全高、全长"),
        ("交期与交货地点","何时之前、送到什么地方")],
}
ASK_NOTE = {"ko":"품목과 노선만 알려주시면 담당자가 배정됩니다.",
            "en":"Tell us the commodity and the route, and we assign a coordinator.",
            "zh":"只需告知品名与航线，我们即刻指派负责人。"}
